version: '3'

services:
  devcontainer:
    image: registry.gitlab.com/currax-data-science/code_space_ml_dev_container:latest
    tty: true
    volumes:
      - ../..:/workspaces:cached
      - ../data/:/app/data
      - ../notebooks/:/app/notebooks
      - ../scripts/:/app/scripts
    ports:
        - "8888:8888"
        - "6006:6006"
    env_file:
     - env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=8888 --no-browser --allow-root
    