version: '3'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - /workspace/data/:/app/data
      - /workspace/notebooks/:/app/notebooks
      - /workspace/scripts/:/app/scripts
    ports:
        - "8888:8888"
        - "6006:6006"
    # env_file:
    #  - ./.env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=8888 --no-browser --allow-root
    