version: '3'

services:
  devcontainer:
    image: registry.gitlab.com/currax-data-science/generative_deep_learning_2nd_edition:5
    tty: true
    volumes:
      - ../..:/workspaces:cached
      - ../data/:/app/data
      - ../notebooks/:/app/notebooks
      - ../scripts/:/app/scripts
    ports:
        - "$JUPYTER_PORT:$JUPYTER_PORT"
        - "$TENSORBOARD_PORT:$TENSORBOARD_PORT"
    env_file:
     - env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=$JUPYTER_PORT --no-browser --allow-root
    