name: Build CoDev Container

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        uses: docker/login-action@v3.0.0
        with:
          registry: registry.gitlab.com
          username: ${{secrets.DOCKER_USER}}
          # Password or personal access token used to log against the Docker registry
          password: ${{secrets.DOCKER_TOKEN}}
          
      - name: Build the Docker image
        run: docker build -t registry.gitlab.com/currax-data-science/generative_deep_learning_2nd_edition:${{github.run_number}} -f docker/Dockerfile.codespace .


      - name: Push Docker Image
        run: docker push registry.gitlab.com/currax-data-science/generative_deep_learning_2nd_edition:${{github.run_number}}

        
